show_for_anons:
  default: true
  type: bool

insert_before_icon:
  default: "search"
  type: string

toggle_width:
  default: 72
  type: integer
  min: 56
  max: 96

toggle_height:
  default: 36
  type: integer
  min: 28
  max: 48

enable_intro_animation:
  default: true
  type: bool
